# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
	"iPhone SE",
	"iPhone 8",
	"iPhone 8 Plus",
	"iPhone X",
	"iPhone XS Max"
])

languages([
	"en",
	"ru",
	"uk"
])

# The name of the scheme which contains the UI Tests
scheme("UITests")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
stop_after_first_error(true)
number_of_retries(0)
concurrent_simulators(false)
clean(true)
skip_open_summary(true)
skip_helper_version_check(true)
reinstall_app(true)
localize_simulator(true)
clear_previous_screenshots(false)

derived_data_path("./fastlane/derived_data_cache")

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
